###########################################################################
## System Clock
###########################################################################
create_clock -period 10.000 -name SYSCLK100_P -waveform {0.000 5.000} [get_ports SYSCLK100_P]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks SYSCLK100_P]
set_property PACKAGE_PIN AV27 [get_ports SYSCLK100_P]
set_property IOSTANDARD LVDS [get_ports SYSCLK100_P]
###########################################################################
## DDR3 Clock
###########################################################################
create_clock -period 5.000 -name ddr3_sys_clk_p -waveform {0.000 2.500} [get_ports ddr3_sys_clk_p]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks ddr3_sys_clk_p]
set_property PACKAGE_PIN H30 [get_ports ddr3_sys_clk_p]
set_property PACKAGE_PIN G30 [get_ports ddr3_sys_clk_n]
set_property IOSTANDARD DIFF_SSTL15 [get_ports ddr3_sys_clk_p]
###########################################################################
## PCIE
###########################################################################
set_property PACKAGE_PIN AL10 [get_ports pcie_ref_p]
create_clock -period 10.000 -name pcie_ref_p -waveform {0.000 5.000} [get_ports pcie_ref_p]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks pcie_ref_p]

set_property PACKAGE_PIN K14 [get_ports sys_rst_n]
set_property IOSTANDARD LVCMOS18 [get_ports sys_rst_n]
set_property PULLUP true [get_ports sys_rst_n]
###########################################################################
## PWM
###########################################################################
set_property PACKAGE_PIN AL16 [get_ports FPGA_PWM_1]
set_property IOSTANDARD LVCMOS18 [get_ports FPGA_PWM_1]
set_property PACKAGE_PIN AL15 [get_ports FPGA_PWM_2]
set_property IOSTANDARD LVCMOS18 [get_ports FPGA_PWM_2]
###########################################################################
## LED
###########################################################################
set_property PACKAGE_PIN AN27 [get_ports LED0_2711_1]
set_property IOSTANDARD LVCMOS18 [get_ports LED0_2711_1]
set_property PACKAGE_PIN AT28 [get_ports LED0_2711_2]
set_property IOSTANDARD LVCMOS18 [get_ports LED0_2711_2]
set_property PACKAGE_PIN AL18 [get_ports LED0_2711_3]
set_property IOSTANDARD LVCMOS18 [get_ports LED0_2711_3]
set_property PACKAGE_PIN AM16 [get_ports LED0_2711_4]
set_property IOSTANDARD LVCMOS18 [get_ports LED0_2711_4]

set_property PACKAGE_PIN AP27 [get_ports LED1_2711_1]
set_property IOSTANDARD LVCMOS18 [get_ports LED1_2711_1]
set_property PACKAGE_PIN AT29 [get_ports LED1_2711_2]
set_property IOSTANDARD LVCMOS18 [get_ports LED1_2711_2]
set_property PACKAGE_PIN AM17 [get_ports LED1_2711_3]
set_property IOSTANDARD LVCMOS18 [get_ports LED1_2711_3]
set_property PACKAGE_PIN AJ16 [get_ports LED1_2711_4]
set_property IOSTANDARD LVCMOS18 [get_ports LED1_2711_4]
###########################################################################
## PPS
###########################################################################
set_property PACKAGE_PIN E12 [get_ports GNSS_ANTON_1V8]
set_property IOSTANDARD LVCMOS18 [get_ports GNSS_ANTON_1V8]
set_property PACKAGE_PIN D12 [get_ports GNSS_RSTN_1V8]
set_property IOSTANDARD LVCMOS18 [get_ports GNSS_RSTN_1V8]
set_property PACKAGE_PIN E14 [get_ports FORCE_ON_1V8]
set_property IOSTANDARD LVCMOS18 [get_ports FORCE_ON_1V8]
set_property PACKAGE_PIN E13 [get_ports GNSS_PPS_1V8]
set_property IOSTANDARD LVCMOS18 [get_ports GNSS_PPS_1V8]

set_property PACKAGE_PIN G15 [get_ports GNSS_RXD_1V8]
set_property IOSTANDARD LVCMOS18 [get_ports GNSS_RXD_1V8]
set_property PACKAGE_PIN F15 [get_ports GNSS_TXD_1V8]
set_property IOSTANDARD LVCMOS18 [get_ports GNSS_TXD_1V8]
###########################################################################
## AD9516
###########################################################################
set_property PACKAGE_PIN AU17 [get_ports SCLK]
set_property IOSTANDARD LVCMOS18 [get_ports SCLK]
set_property PACKAGE_PIN AP16 [get_ports RESET_B]
set_property IOSTANDARD LVCMOS18 [get_ports RESET_B]
set_property PACKAGE_PIN AR17 [get_ports SDIO]
set_property IOSTANDARD LVCMOS18 [get_ports SDIO]
set_property PACKAGE_PIN AM18 [get_ports SDO]
set_property IOSTANDARD LVCMOS18 [get_ports SDO]
set_property PACKAGE_PIN AT16 [get_ports REFSEL]
set_property IOSTANDARD LVCMOS18 [get_ports REFSEL]
set_property PACKAGE_PIN AT15 [get_ports CS]
set_property IOSTANDARD LVCMOS18 [get_ports CS]
###########################################################################
## AD7606
###########################################################################
set_property PACKAGE_PIN AY17 [get_ports AD7606_RESET_1V8]
set_property PACKAGE_PIN BB18 [get_ports AD7606_CONVSTA_1V8]
set_property PACKAGE_PIN BA18 [get_ports AD7606_CONVSTB_1V8]
set_property PACKAGE_PIN AT18 [get_ports AD7606_BUSY_1V8]
set_property PACKAGE_PIN BD17 [get_ports AD7606_FRSTDATA_1V8]

set_property PACKAGE_PIN BB17 [get_ports AD7606_CS_1V8]
set_property PACKAGE_PIN AY18 [get_ports AD7606_RD_1V8]

set_property PACKAGE_PIN BD15 [get_ports {AD7606_DB_1V8[15]}]
set_property PACKAGE_PIN BC18 [get_ports {AD7606_DB_1V8[14]}]
set_property PACKAGE_PIN BD16 [get_ports {AD7606_DB_1V8[13]}]
set_property PACKAGE_PIN BB15 [get_ports {AD7606_DB_1V8[12]}]
set_property PACKAGE_PIN BC15 [get_ports {AD7606_DB_1V8[11]}]
set_property PACKAGE_PIN BA16 [get_ports {AD7606_DB_1V8[10]}]
set_property PACKAGE_PIN BB16 [get_ports {AD7606_DB_1V8[9]}]
set_property PACKAGE_PIN BA15 [get_ports {AD7606_DB_1V8[8]}]
set_property PACKAGE_PIN AW16 [get_ports {AD7606_DB_1V8[7]}]
set_property PACKAGE_PIN AW15 [get_ports {AD7606_DB_1V8[6]}]
set_property PACKAGE_PIN AV15 [get_ports {AD7606_DB_1V8[5]}]
set_property PACKAGE_PIN AU15 [get_ports {AD7606_DB_1V8[4]}]
set_property PACKAGE_PIN AV17 [get_ports {AD7606_DB_1V8[3]}]
set_property PACKAGE_PIN AP17 [get_ports {AD7606_DB_1V8[2]}]
set_property PACKAGE_PIN AN17 [get_ports {AD7606_DB_1V8[1]}]
set_property PACKAGE_PIN AY16 [get_ports {AD7606_DB_1V8[0]}]

set_property PACKAGE_PIN AU18 [get_ports {AD7606_OS_1V8[2]}]
set_property PACKAGE_PIN AV18 [get_ports {AD7606_OS_1V8[1]}]
set_property PACKAGE_PIN AW17 [get_ports {AD7606_OS_1V8[0]}]

set_property PACKAGE_PIN AK18 [get_ports ADC_OE1_B]
set_property PACKAGE_PIN BC19 [get_ports ADC_OE2_B]
set_property PACKAGE_PIN BC17 [get_ports ADC_OE3_B]
#µÁ∆Ω
set_property IOSTANDARD LVCMOS18 [get_ports AD7606_BUSY_1V8]
set_property IOSTANDARD LVCMOS18 [get_ports AD7606_CONVSTA_1V8]
set_property IOSTANDARD LVCMOS18 [get_ports AD7606_CONVSTB_1V8]
set_property IOSTANDARD LVCMOS18 [get_ports AD7606_CS_1V8]
set_property IOSTANDARD LVCMOS18 [get_ports AD7606_FRSTDATA_1V8]

set_property IOSTANDARD LVCMOS18 [get_ports AD7606_RD_1V8]
set_property IOSTANDARD LVCMOS18 [get_ports AD7606_RESET_1V8]

set_property IOSTANDARD LVCMOS18 [get_ports {AD7606_DB_1V8[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AD7606_DB_1V8[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AD7606_DB_1V8[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AD7606_DB_1V8[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AD7606_DB_1V8[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AD7606_DB_1V8[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AD7606_DB_1V8[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AD7606_DB_1V8[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AD7606_DB_1V8[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AD7606_DB_1V8[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AD7606_DB_1V8[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AD7606_DB_1V8[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AD7606_DB_1V8[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AD7606_DB_1V8[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AD7606_DB_1V8[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AD7606_DB_1V8[0]}]

set_property IOSTANDARD LVCMOS18 [get_ports {AD7606_OS_1V8[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AD7606_OS_1V8[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AD7606_OS_1V8[0]}]

set_property IOSTANDARD LVCMOS18 [get_ports ADC_OE1_B]
set_property IOSTANDARD LVCMOS18 [get_ports ADC_OE2_B]
set_property IOSTANDARD LVCMOS18 [get_ports ADC_OE3_B]
###########################################################################
## UART
###########################################################################
set_property PACKAGE_PIN AL29 [get_ports {UART_TXD_RS422[0]}]
set_property PACKAGE_PIN AJ29 [get_ports {UART_TXD_RS422[1]}]
set_property PACKAGE_PIN AL28 [get_ports {UART_TXD_RS422[2]}]
set_property PACKAGE_PIN AM28 [get_ports {UART_TXD_RS422[3]}]
set_property PACKAGE_PIN AN28 [get_ports {UART_TXD_RS422[4]}]
set_property PACKAGE_PIN AN29 [get_ports {UART_TXD_RS422[5]}]

set_property PACKAGE_PIN AM30 [get_ports {UART_RXD_RS422[0]}]
set_property PACKAGE_PIN AK29 [get_ports {UART_RXD_RS422[1]}]
set_property PACKAGE_PIN AK27 [get_ports {UART_RXD_RS422[2]}]
set_property PACKAGE_PIN AN30 [get_ports {UART_RXD_RS422[3]}]
set_property PACKAGE_PIN AM27 [get_ports {UART_RXD_RS422[4]}]
set_property PACKAGE_PIN AR29 [get_ports {UART_RXD_RS422[5]}]

set_property IOSTANDARD LVCMOS18 [get_ports {UART_RXD_RS422[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {UART_RXD_RS422[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {UART_RXD_RS422[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {UART_RXD_RS422[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {UART_RXD_RS422[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {UART_RXD_RS422[0]}]

set_property IOSTANDARD LVCMOS18 [get_ports {UART_TXD_RS422[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {UART_TXD_RS422[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {UART_TXD_RS422[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {UART_TXD_RS422[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {UART_TXD_RS422[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {UART_TXD_RS422[0]}]

set_property PACKAGE_PIN AR28 [get_ports UART_PPS_OE]
set_property PACKAGE_PIN AK28 [get_ports UART_CON_OE]
set_property IOSTANDARD LVCMOS18 [get_ports UART_PPS_OE]
set_property IOSTANDARD LVCMOS18 [get_ports UART_CON_OE]
###########################################################################
## 2711
###########################################################################
set_property PACKAGE_PIN AN15 [get_ports POWER_ON]
set_property IOSTANDARD LVCMOS18 [get_ports POWER_ON]

set_property PACKAGE_PIN AU25 [get_ports LVDS_1_2711_P]
set_property IOSTANDARD LVDS [get_ports LVDS_1_2711_P]
create_clock -period 10.000 -name LVDS_1_2711_P -waveform {0.000 5.000} [get_ports LVDS_1_2711_P]
set_property PACKAGE_PIN AU20 [get_ports LVDS_2_2711_P]
set_property IOSTANDARD LVDS [get_ports LVDS_2_2711_P]
create_clock -period 10.000 -name LVDS_2_2711_P -waveform {0.000 5.000} [get_ports LVDS_2_2711_P]
###########################################################################
## 2711_ch1
###########################################################################
set_property PACKAGE_PIN BC24 [get_ports {OE[0]}]
set_property PACKAGE_PIN BD24 [get_ports {OE[1]}]
set_property PACKAGE_PIN BA23 [get_ports {OE[2]}]
set_property PACKAGE_PIN AL23 [get_ports {OE[3]}]
set_property PACKAGE_PIN AL25 [get_ports {OE[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {OE[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {OE[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {OE[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {OE[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {OE[4]}]

set_property PACKAGE_PIN AT23 [get_ports {GTX_CLK[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GTX_CLK[0]}]

set_property PACKAGE_PIN AV23 [get_ports {RX_CLK[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX_CLK[0]}]

set_property PACKAGE_PIN AL24 [get_ports {LOOP_EN[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LOOP_EN[0]}]

set_property PACKAGE_PIN AJ25 [get_ports {ENABLE[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ENABLE[0]}]

set_property PACKAGE_PIN BC23 [get_ports {LCKREFN[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LCKREFN[0]}]

set_property PACKAGE_PIN BB23 [get_ports {PRBSEN[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {PRBSEN[0]}]

set_property PACKAGE_PIN AN23 [get_ports {PRE[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {PRE[0]}]

set_property PACKAGE_PIN AJ26 [get_ports {RKLSB[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RKLSB[0]}]
set_property PACKAGE_PIN AK26 [get_ports {RKMSB[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RKMSB[0]}]

set_property PACKAGE_PIN AU27 [get_ports {TKLSB[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TKLSB[0]}]
set_property PACKAGE_PIN AU23 [get_ports {TKMSB[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TKMSB[0]}]

set_property PACKAGE_PIN AY23 [get_ports {TX_Data[0]}]
set_property PACKAGE_PIN BA24 [get_ports {TX_Data[1]}]
set_property PACKAGE_PIN BC25 [get_ports {TX_Data[2]}]
set_property PACKAGE_PIN BD25 [get_ports {TX_Data[3]}]
set_property PACKAGE_PIN BB25 [get_ports {TX_Data[4]}]
set_property PACKAGE_PIN BB26 [get_ports {TX_Data[5]}]
set_property PACKAGE_PIN BD26 [get_ports {TX_Data[6]}]
set_property PACKAGE_PIN AY26 [get_ports {TX_Data[7]}]
set_property PACKAGE_PIN BA26 [get_ports {TX_Data[8]}]
set_property PACKAGE_PIN BA25 [get_ports {TX_Data[9]}]
set_property PACKAGE_PIN AW24 [get_ports {TX_Data[10]}]
set_property PACKAGE_PIN AY24 [get_ports {TX_Data[11]}]
set_property PACKAGE_PIN AW26 [get_ports {TX_Data[12]}]
set_property PACKAGE_PIN AW25 [get_ports {TX_Data[13]}]
set_property PACKAGE_PIN AV25 [get_ports {TX_Data[14]}]
set_property PACKAGE_PIN AV24 [get_ports {TX_Data[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TX_Data[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TX_Data[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TX_Data[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TX_Data[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TX_Data[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TX_Data[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TX_Data[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TX_Data[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TX_Data[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TX_Data[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TX_Data[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TX_Data[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TX_Data[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TX_Data[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TX_Data[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TX_Data[15]}]

set_property PACKAGE_PIN AM23 [get_ports {RX_Data[0]}]
set_property PACKAGE_PIN AT24 [get_ports {RX_Data[1]}]
set_property PACKAGE_PIN AP24 [get_ports {RX_Data[2]}]
set_property PACKAGE_PIN AR24 [get_ports {RX_Data[3]}]
set_property PACKAGE_PIN AT25 [get_ports {RX_Data[4]}]
set_property PACKAGE_PIN AT26 [get_ports {RX_Data[5]}]
set_property PACKAGE_PIN AP25 [get_ports {RX_Data[6]}]
set_property PACKAGE_PIN AP26 [get_ports {RX_Data[7]}]
set_property PACKAGE_PIN AN24 [get_ports {RX_Data[8]}]
set_property PACKAGE_PIN AR26 [get_ports {RX_Data[9]}]
set_property PACKAGE_PIN AM26 [get_ports {RX_Data[10]}]
set_property PACKAGE_PIN AN25 [get_ports {RX_Data[11]}]
set_property PACKAGE_PIN AM25 [get_ports {RX_Data[12]}]
set_property PACKAGE_PIN AL26 [get_ports {RX_Data[13]}]
set_property PACKAGE_PIN AK23 [get_ports {RX_Data[14]}]
set_property PACKAGE_PIN AK24 [get_ports {RX_Data[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX_Data[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX_Data[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX_Data[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX_Data[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX_Data[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX_Data[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX_Data[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX_Data[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX_Data[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX_Data[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX_Data[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX_Data[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX_Data[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX_Data[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX_Data[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX_Data[15]}]

###########################################################################
## 2711_ch2
###########################################################################
set_property PACKAGE_PIN AW34 [get_ports {OE[5]}]
set_property PACKAGE_PIN BD31 [get_ports {OE[6]}]
set_property PACKAGE_PIN AK32 [get_ports {OE[7]}]
set_property PACKAGE_PIN AL31 [get_ports {OE[8]}]
set_property PACKAGE_PIN BA35 [get_ports {OE[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {OE[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {OE[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {OE[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {OE[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {OE[9]}]

set_property PACKAGE_PIN AU33 [get_ports {GTX_CLK[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GTX_CLK[1]}]

set_property PACKAGE_PIN AV32 [get_ports {RX_CLK[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX_CLK[1]}]

set_property PACKAGE_PIN AK31 [get_ports {LOOP_EN[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LOOP_EN[1]}]

set_property PACKAGE_PIN AJ32 [get_ports {ENABLE[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ENABLE[1]}]

set_property PACKAGE_PIN AJ30 [get_ports {LCKREFN[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LCKREFN[1]}]

set_property PACKAGE_PIN AU31 [get_ports {PRBSEN[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {PRBSEN[1]}]

set_property PACKAGE_PIN AJ31 [get_ports {PRE[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {PRE[1]}]

set_property PACKAGE_PIN AY33 [get_ports {RKLSB[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RKLSB[1]}]
set_property PACKAGE_PIN AY34 [get_ports {RKMSB[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RKMSB[1]}]

set_property PACKAGE_PIN AM31 [get_ports {TKLSB[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TKLSB[1]}]
set_property PACKAGE_PIN AK33 [get_ports {TKMSB[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TKMSB[1]}]

set_property PACKAGE_PIN AW35 [get_ports {TX_Data[16]}]
set_property PACKAGE_PIN AV33 [get_ports {TX_Data[17]}]
set_property PACKAGE_PIN AV35 [get_ports {TX_Data[18]}]
set_property PACKAGE_PIN AV34 [get_ports {TX_Data[19]}]
set_property PACKAGE_PIN AU32 [get_ports {TX_Data[20]}]
set_property PACKAGE_PIN AR31 [get_ports {TX_Data[21]}]
set_property PACKAGE_PIN AT33 [get_ports {TX_Data[22]}]
set_property PACKAGE_PIN AR33 [get_ports {TX_Data[23]}]
set_property PACKAGE_PIN AP31 [get_ports {TX_Data[24]}]
set_property PACKAGE_PIN AR32 [get_ports {TX_Data[25]}]
set_property PACKAGE_PIN AN32 [get_ports {TX_Data[26]}]
set_property PACKAGE_PIN AP32 [get_ports {TX_Data[27]}]
set_property PACKAGE_PIN AN33 [get_ports {TX_Data[28]}]
set_property PACKAGE_PIN AM33 [get_ports {TX_Data[29]}]
set_property PACKAGE_PIN AM32 [get_ports {TX_Data[30]}]
set_property PACKAGE_PIN AL33 [get_ports {TX_Data[31]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TX_Data[16]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TX_Data[17]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TX_Data[18]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TX_Data[19]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TX_Data[20]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TX_Data[21]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TX_Data[22]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TX_Data[23]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TX_Data[24]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TX_Data[25]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TX_Data[26]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TX_Data[27]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TX_Data[28]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TX_Data[29]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TX_Data[30]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TX_Data[31]}]

set_property PACKAGE_PIN AW32 [get_ports {RX_Data[16]}]
set_property PACKAGE_PIN AL30 [get_ports {RX_Data[17]}]
set_property PACKAGE_PIN BB32 [get_ports {RX_Data[18]}]
set_property PACKAGE_PIN BB31 [get_ports {RX_Data[19]}]
set_property PACKAGE_PIN BC32 [get_ports {RX_Data[20]}]
set_property PACKAGE_PIN AY32 [get_ports {RX_Data[21]}]
set_property PACKAGE_PIN BD32 [get_ports {RX_Data[22]}]
set_property PACKAGE_PIN BB33 [get_ports {RX_Data[23]}]
set_property PACKAGE_PIN BC33 [get_ports {RX_Data[24]}]
set_property PACKAGE_PIN BA33 [get_ports {RX_Data[25]}]
set_property PACKAGE_PIN BC34 [get_ports {RX_Data[26]}]
set_property PACKAGE_PIN BD34 [get_ports {RX_Data[27]}]
set_property PACKAGE_PIN BA34 [get_ports {RX_Data[28]}]
set_property PACKAGE_PIN BD35 [get_ports {RX_Data[29]}]
set_property PACKAGE_PIN BC35 [get_ports {RX_Data[30]}]
set_property PACKAGE_PIN BB35 [get_ports {RX_Data[31]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX_Data[16]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX_Data[17]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX_Data[18]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX_Data[19]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX_Data[20]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX_Data[21]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX_Data[22]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX_Data[23]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX_Data[24]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX_Data[25]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX_Data[26]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX_Data[27]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX_Data[28]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX_Data[29]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX_Data[30]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX_Data[31]}]

###########################################################################
## 2711_ch3
###########################################################################
set_property PACKAGE_PIN AK22 [get_ports {OE[10]}]
set_property PACKAGE_PIN AM22 [get_ports {OE[11]}]
set_property PACKAGE_PIN AN22 [get_ports {OE[12]}]
set_property PACKAGE_PIN AT20 [get_ports {OE[13]}]
set_property PACKAGE_PIN AR23 [get_ports {OE[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {OE[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {OE[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {OE[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {OE[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {OE[14]}]

set_property PACKAGE_PIN AT21 [get_ports {GTX_CLK[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GTX_CLK[2]}]

set_property PACKAGE_PIN AU22 [get_ports {RX_CLK[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX_CLK[2]}]

set_property PACKAGE_PIN AJ22 [get_ports {LOOP_EN[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LOOP_EN[2]}]

set_property PACKAGE_PIN AP22 [get_ports {ENABLE[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ENABLE[2]}]

set_property PACKAGE_PIN AK19 [get_ports {LCKREFN[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LCKREFN[2]}]

set_property PACKAGE_PIN AK21 [get_ports {PRBSEN[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {PRBSEN[2]}]

set_property PACKAGE_PIN AJ21 [get_ports {PRE[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {PRE[2]}]

set_property PACKAGE_PIN BD22 [get_ports {RKLSB[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RKLSB[2]}]
set_property PACKAGE_PIN AR22 [get_ports {RKMSB[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RKMSB[2]}]

set_property PACKAGE_PIN AW22 [get_ports {TKLSB[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TKLSB[2]}]
set_property PACKAGE_PIN AV22 [get_ports {TKMSB[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TKMSB[2]}]

set_property PACKAGE_PIN AR21 [get_ports {TX_Data[32]}]
set_property PACKAGE_PIN AU21 [get_ports {TX_Data[33]}]
set_property PACKAGE_PIN AV20 [get_ports {TX_Data[34]}]
set_property PACKAGE_PIN AW19 [get_ports {TX_Data[35]}]
set_property PACKAGE_PIN AW21 [get_ports {TX_Data[36]}]
set_property PACKAGE_PIN AY21 [get_ports {TX_Data[37]}]
set_property PACKAGE_PIN AY19 [get_ports {TX_Data[38]}]
set_property PACKAGE_PIN BD19 [get_ports {TX_Data[39]}]
set_property PACKAGE_PIN BA19 [get_ports {TX_Data[40]}]
set_property PACKAGE_PIN BA20 [get_ports {TX_Data[41]}]
set_property PACKAGE_PIN BC20 [get_ports {TX_Data[42]}]
set_property PACKAGE_PIN BA21 [get_ports {TX_Data[43]}]
set_property PACKAGE_PIN BB20 [get_ports {TX_Data[44]}]
set_property PACKAGE_PIN BB22 [get_ports {TX_Data[45]}]
set_property PACKAGE_PIN BB21 [get_ports {TX_Data[46]}]
set_property PACKAGE_PIN AY22 [get_ports {TX_Data[47]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TX_Data[32]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TX_Data[33]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TX_Data[34]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TX_Data[35]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TX_Data[36]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TX_Data[37]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TX_Data[38]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TX_Data[39]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TX_Data[40]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TX_Data[41]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TX_Data[42]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TX_Data[43]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TX_Data[44]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TX_Data[45]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TX_Data[46]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TX_Data[47]}]

set_property PACKAGE_PIN AL21 [get_ports {RX_Data[32]}]
set_property PACKAGE_PIN AL20 [get_ports {RX_Data[33]}]
set_property PACKAGE_PIN AL19 [get_ports {RX_Data[34]}]
set_property PACKAGE_PIN AM21 [get_ports {RX_Data[35]}]
set_property PACKAGE_PIN AM20 [get_ports {RX_Data[36]}]
set_property PACKAGE_PIN AN20 [get_ports {RX_Data[37]}]
set_property PACKAGE_PIN AN19 [get_ports {RX_Data[38]}]
set_property PACKAGE_PIN AP19 [get_ports {RX_Data[39]}]
set_property PACKAGE_PIN AR19 [get_ports {RX_Data[40]}]
set_property PACKAGE_PIN AP20 [get_ports {RX_Data[41]}]
set_property PACKAGE_PIN AW20 [get_ports {RX_Data[42]}]
set_property PACKAGE_PIN AT19 [get_ports {RX_Data[43]}]
set_property PACKAGE_PIN BD20 [get_ports {RX_Data[44]}]
set_property PACKAGE_PIN AP21 [get_ports {RX_Data[45]}]
set_property PACKAGE_PIN BD21 [get_ports {RX_Data[46]}]
set_property PACKAGE_PIN BC22 [get_ports {RX_Data[47]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX_Data[32]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX_Data[33]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX_Data[34]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX_Data[35]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX_Data[36]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX_Data[37]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX_Data[38]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX_Data[39]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX_Data[40]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX_Data[41]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX_Data[42]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX_Data[43]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX_Data[44]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX_Data[45]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX_Data[46]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX_Data[47]}]
###########################################################################
## 2711_ch3
###########################################################################
set_property PACKAGE_PIN AJ14 [get_ports {OE[15]}]
set_property PACKAGE_PIN AK14 [get_ports {OE[16]}]
set_property PACKAGE_PIN AK12 [get_ports {OE[17]}]
set_property PACKAGE_PIN AK13 [get_ports {OE[18]}]
set_property PACKAGE_PIN AL13 [get_ports {OE[19]}]
set_property IOSTANDARD LVCMOS18 [get_ports {OE[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {OE[16]}]
set_property IOSTANDARD LVCMOS18 [get_ports {OE[17]}]
set_property IOSTANDARD LVCMOS18 [get_ports {OE[18]}]
set_property IOSTANDARD LVCMOS18 [get_ports {OE[19]}]

set_property PACKAGE_PIN AU13 [get_ports {GTX_CLK[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GTX_CLK[3]}]

set_property PACKAGE_PIN AV14 [get_ports {RX_CLK[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX_CLK[3]}]

set_property PACKAGE_PIN AL14 [get_ports {LOOP_EN[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LOOP_EN[3]}]

set_property PACKAGE_PIN BD14 [get_ports {ENABLE[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ENABLE[3]}]

set_property PACKAGE_PIN AN12 [get_ports {LCKREFN[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LCKREFN[3]}]

set_property PACKAGE_PIN AM12 [get_ports {PRBSEN[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {PRBSEN[3]}]

set_property PACKAGE_PIN AM13 [get_ports {PRE[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {PRE[3]}]

set_property PACKAGE_PIN BC13 [get_ports {RKLSB[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RKLSB[3]}]
set_property PACKAGE_PIN BA14 [get_ports {RKMSB[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RKMSB[3]}]

set_property PACKAGE_PIN BA10 [get_ports {TKLSB[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TKLSB[3]}]
set_property PACKAGE_PIN BC14 [get_ports {TKMSB[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TKMSB[3]}]

set_property PACKAGE_PIN AN14 [get_ports {TX_Data[48]}]
set_property PACKAGE_PIN AP14 [get_ports {TX_Data[49]}]
set_property PACKAGE_PIN AT14 [get_ports {TX_Data[50]}]
set_property PACKAGE_PIN AR13 [get_ports {TX_Data[51]}]
set_property PACKAGE_PIN AR12 [get_ports {TX_Data[52]}]
set_property PACKAGE_PIN AT13 [get_ports {TX_Data[53]}]
set_property PACKAGE_PIN AU12 [get_ports {TX_Data[54]}]
set_property PACKAGE_PIN AU10 [get_ports {TX_Data[55]}]
set_property PACKAGE_PIN AU11 [get_ports {TX_Data[56]}]
set_property PACKAGE_PIN AV10 [get_ports {TX_Data[57]}]
set_property PACKAGE_PIN AW10 [get_ports {TX_Data[58]}]
set_property PACKAGE_PIN AW11 [get_ports {TX_Data[59]}]
set_property PACKAGE_PIN AV13 [get_ports {TX_Data[60]}]
set_property PACKAGE_PIN AY13 [get_ports {TX_Data[61]}]
set_property PACKAGE_PIN AW12 [get_ports {TX_Data[62]}]
set_property PACKAGE_PIN BA13 [get_ports {TX_Data[63]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TX_Data[48]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TX_Data[49]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TX_Data[50]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TX_Data[51]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TX_Data[52]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TX_Data[53]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TX_Data[54]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TX_Data[55]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TX_Data[56]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TX_Data[57]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TX_Data[58]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TX_Data[59]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TX_Data[60]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TX_Data[61]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TX_Data[62]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TX_Data[63]}]

set_property PACKAGE_PIN AN13 [get_ports {RX_Data[48]}]
set_property PACKAGE_PIN AV12 [get_ports {RX_Data[49]}]
set_property PACKAGE_PIN AW14 [get_ports {RX_Data[50]}]
set_property PACKAGE_PIN AY14 [get_ports {RX_Data[51]}]
set_property PACKAGE_PIN AY11 [get_ports {RX_Data[52]}]
set_property PACKAGE_PIN AY12 [get_ports {RX_Data[53]}]
set_property PACKAGE_PIN BA11 [get_ports {RX_Data[54]}]
set_property PACKAGE_PIN BB11 [get_ports {RX_Data[55]}]
set_property PACKAGE_PIN BB10 [get_ports {RX_Data[56]}]
set_property PACKAGE_PIN BB12 [get_ports {RX_Data[57]}]
set_property PACKAGE_PIN BC10 [get_ports {RX_Data[58]}]
set_property PACKAGE_PIN BD10 [get_ports {RX_Data[59]}]
set_property PACKAGE_PIN BB13 [get_ports {RX_Data[60]}]
set_property PACKAGE_PIN BC12 [get_ports {RX_Data[61]}]
set_property PACKAGE_PIN BD11 [get_ports {RX_Data[62]}]
set_property PACKAGE_PIN BD12 [get_ports {RX_Data[63]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX_Data[48]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX_Data[49]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX_Data[50]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX_Data[51]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX_Data[52]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX_Data[53]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX_Data[54]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX_Data[55]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX_Data[56]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX_Data[57]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX_Data[58]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX_Data[59]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX_Data[60]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX_Data[61]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX_Data[62]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RX_Data[63]}]
###########################################################################
## FLASH SPIx4
###########################################################################
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property CONFIG_MODE SPIx4 [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property CONFIG_VOLTAGE 1.8 [current_design]
set_property CFGBVS GND [current_design]


