###########################################################################
## sys clk
###########################################################################
set_property PACKAGE_PIN T26 [get_ports SYSCLK]
set_property IOSTANDARD LVCMOS33 [get_ports SYSCLK]
create_clock -period 10.000 -name SYSCLK -waveform {0.000 5.000} [get_ports SYSCLK]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks SYSCLK]

set_property PACKAGE_PIN K28 [get_ports SYSCLK_P]
set_property PACKAGE_PIN K29 [get_ports SYSCLK_N]
set_property IOSTANDARD LVDS_25 [get_ports SYSCLK_P]
create_clock -period 10.000 -name SYSCLK_P -waveform {0.000 5.000} [get_ports SYSCLK_P]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks SYSCLK_P]

set_property PACKAGE_PIN U27 [get_ports K7_REFCLK_P]
set_property PACKAGE_PIN U28 [get_ports K7_REFCLK_N]
set_property IOSTANDARD LVDS_25 [get_ports K7_REFCLK_P]
create_clock -period 10.000 -name K7_REFCLK_P -waveform {0.000 5.000} [get_ports K7_REFCLK_P]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks K7_REFCLK_P]

###########################################################################
## ad7656
###########################################################################
set_property PACKAGE_PIN K26 [get_ports adc_trigger_gpio]
set_property IOSTANDARD LVCMOS33 [get_ports adc_trigger_gpio]

set_property PACKAGE_PIN F28 [get_ports ADC1_CS_FPGA]
set_property PACKAGE_PIN E28 [get_ports ADC1_CONVST_FPGA]
set_property PACKAGE_PIN F27 [get_ports ADC1_RESET_FPGA]
set_property PACKAGE_PIN G28 [get_ports ADC1_RD_FPGA]
set_property PACKAGE_PIN H24 [get_ports WR_1_FPGA]
set_property PACKAGE_PIN F26 [get_ports ADC1_BUSY_FPGA]
set_property PACKAGE_PIN D29 [get_ports {ADC1_DB[0]}]
set_property PACKAGE_PIN E26 [get_ports {ADC1_DB[1]}]
set_property PACKAGE_PIN C29 [get_ports {ADC1_DB[2]}]
set_property PACKAGE_PIN C30 [get_ports {ADC1_DB[3]}]
set_property PACKAGE_PIN D28 [get_ports {ADC1_DB[4]}]
set_property PACKAGE_PIN B30 [get_ports {ADC1_DB[5]}]
set_property PACKAGE_PIN A30 [get_ports {ADC1_DB[6]}]
set_property PACKAGE_PIN B29 [get_ports {ADC1_DB[7]}]
set_property PACKAGE_PIN B28 [get_ports {ADC1_DB[8]}]
set_property PACKAGE_PIN A28 [get_ports {ADC1_DB[9]}]
set_property PACKAGE_PIN D27 [get_ports {ADC1_DB[10]}]
set_property PACKAGE_PIN A27 [get_ports {ADC1_DB[11]}]
set_property PACKAGE_PIN C26 [get_ports {ADC1_DB[12]}]
set_property PACKAGE_PIN A26 [get_ports {ADC1_DB[13]}]
set_property PACKAGE_PIN D26 [get_ports {ADC1_DB[14]}]
set_property PACKAGE_PIN C24 [get_ports {ADC1_DB[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports ADC1_CS_FPGA]
set_property IOSTANDARD LVCMOS33 [get_ports ADC1_CONVST_FPGA]
set_property IOSTANDARD LVCMOS33 [get_ports ADC1_RESET_FPGA]
set_property IOSTANDARD LVCMOS33 [get_ports ADC1_RD_FPGA]
set_property IOSTANDARD LVCMOS33 [get_ports WR_1_FPGA]
set_property IOSTANDARD LVCMOS33 [get_ports ADC1_BUSY_FPGA]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC1_DB[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC1_DB[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC1_DB[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC1_DB[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC1_DB[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC1_DB[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC1_DB[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC1_DB[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC1_DB[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC1_DB[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC1_DB[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC1_DB[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC1_DB[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC1_DB[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC1_DB[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC1_DB[15]}]

set_property PACKAGE_PIN G27 [get_ports ADC2_CS_FPGA]
set_property PACKAGE_PIN G29 [get_ports ADC2_CONVST_FPGA]
set_property PACKAGE_PIN H26 [get_ports ADC2_RESET_FPGA]
set_property PACKAGE_PIN H27 [get_ports ADC2_RD_FPGA]
set_property PACKAGE_PIN G23 [get_ports WR_2_FPGA]
set_property PACKAGE_PIN F23 [get_ports ADC2_BUSY_FPGA]
set_property PACKAGE_PIN E25 [get_ports {ADC2_DB[0]}]
set_property PACKAGE_PIN F25 [get_ports {ADC2_DB[1]}]
set_property PACKAGE_PIN E29 [get_ports {ADC2_DB[2]}]
set_property PACKAGE_PIN F30 [get_ports {ADC2_DB[3]}]
set_property PACKAGE_PIN E24 [get_ports {ADC2_DB[4]}]
set_property PACKAGE_PIN E30 [get_ports {ADC2_DB[5]}]
set_property PACKAGE_PIN C27 [get_ports {ADC2_DB[6]}]
set_property PACKAGE_PIN D24 [get_ports {ADC2_DB[7]}]
set_property PACKAGE_PIN C25 [get_ports {ADC2_DB[8]}]
set_property PACKAGE_PIN B27 [get_ports {ADC2_DB[9]}]
set_property PACKAGE_PIN B25 [get_ports {ADC2_DB[10]}]
set_property PACKAGE_PIN E23 [get_ports {ADC2_DB[11]}]
set_property PACKAGE_PIN D23 [get_ports {ADC2_DB[12]}]
set_property PACKAGE_PIN B24 [get_ports {ADC2_DB[13]}]
set_property PACKAGE_PIN B23 [get_ports {ADC2_DB[14]}]
set_property PACKAGE_PIN A23 [get_ports {ADC2_DB[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports ADC2_CS_FPGA]
set_property IOSTANDARD LVCMOS33 [get_ports ADC2_CONVST_FPGA]
set_property IOSTANDARD LVCMOS33 [get_ports ADC2_RESET_FPGA]
set_property IOSTANDARD LVCMOS33 [get_ports ADC2_RD_FPGA]
set_property IOSTANDARD LVCMOS33 [get_ports WR_2_FPGA]
set_property IOSTANDARD LVCMOS33 [get_ports ADC2_BUSY_FPGA]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC2_DB[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC2_DB[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC2_DB[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC2_DB[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC2_DB[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC2_DB[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC2_DB[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC2_DB[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC2_DB[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC2_DB[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC2_DB[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC2_DB[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC2_DB[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC2_DB[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC2_DB[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC2_DB[15]}]

set_property PACKAGE_PIN Y30 [get_ports ADC3_CS_FPGA]
set_property PACKAGE_PIN Y29 [get_ports ADC3_CONVST_FPGA]
set_property PACKAGE_PIN AA30 [get_ports ADC3_RESET_FPGA]
set_property PACKAGE_PIN AA26 [get_ports ADC3_RD_FPGA]
set_property PACKAGE_PIN AB30 [get_ports WR_3_FPGA]
set_property PACKAGE_PIN AA28 [get_ports ADC3_BUSY_FPGA]
set_property PACKAGE_PIN AF26 [get_ports {ADC3_DB[0]}]
set_property PACKAGE_PIN Y28 [get_ports {ADC3_DB[1]}]
set_property PACKAGE_PIN AD27 [get_ports {ADC3_DB[2]}]
set_property PACKAGE_PIN AC26 [get_ports {ADC3_DB[3]}]
set_property PACKAGE_PIN AE28 [get_ports {ADC3_DB[4]}]
set_property PACKAGE_PIN AC27 [get_ports {ADC3_DB[5]}]
set_property PACKAGE_PIN AB27 [get_ports {ADC3_DB[6]}]
set_property PACKAGE_PIN AD28 [get_ports {ADC3_DB[7]}]
set_property PACKAGE_PIN AA27 [get_ports {ADC3_DB[8]}]
set_property PACKAGE_PIN AB28 [get_ports {ADC3_DB[9]}]
set_property PACKAGE_PIN Y26 [get_ports {ADC3_DB[10]}]
set_property PACKAGE_PIN AA25 [get_ports {ADC3_DB[11]}]
set_property PACKAGE_PIN W28 [get_ports {ADC3_DB[12]}]
set_property PACKAGE_PIN W29 [get_ports {ADC3_DB[13]}]
set_property PACKAGE_PIN Y25 [get_ports {ADC3_DB[14]}]
set_property PACKAGE_PIN W27 [get_ports {ADC3_DB[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports ADC3_CS_FPGA]
set_property IOSTANDARD LVCMOS33 [get_ports ADC3_CONVST_FPGA]
set_property IOSTANDARD LVCMOS33 [get_ports ADC3_RESET_FPGA]
set_property IOSTANDARD LVCMOS33 [get_ports ADC3_RD_FPGA]
set_property IOSTANDARD LVCMOS33 [get_ports WR_3_FPGA]
set_property IOSTANDARD LVCMOS33 [get_ports ADC3_BUSY_FPGA]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC3_DB[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC3_DB[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC3_DB[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC3_DB[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC3_DB[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC3_DB[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC3_DB[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC3_DB[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC3_DB[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC3_DB[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC3_DB[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC3_DB[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC3_DB[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC3_DB[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC3_DB[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC3_DB[15]}]

set_property PACKAGE_PIN AK28 [get_ports ADC4_CS_FPGA]
set_property PACKAGE_PIN AJ28 [get_ports ADC4_CONVST_FPGA]
set_property PACKAGE_PIN AH27 [get_ports ADC4_RESET_FPGA]
set_property PACKAGE_PIN AJ27 [get_ports ADC4_RD_FPGA]
set_property PACKAGE_PIN AH26 [get_ports WR_4_FPGA]
set_property PACKAGE_PIN AG27 [get_ports ADC4_BUSY_FPGA]
set_property PACKAGE_PIN AJ29 [get_ports {ADC4_DB[0]}]
set_property PACKAGE_PIN AK29 [get_ports {ADC4_DB[1]}]
set_property PACKAGE_PIN AG28 [get_ports {ADC4_DB[2]}]
set_property PACKAGE_PIN AK30 [get_ports {ADC4_DB[3]}]
set_property PACKAGE_PIN AH30 [get_ports {ADC4_DB[4]}]
set_property PACKAGE_PIN AH29 [get_ports {ADC4_DB[5]}]
set_property PACKAGE_PIN AG30 [get_ports {ADC4_DB[6]}]
set_property PACKAGE_PIN AG29 [get_ports {ADC4_DB[7]}]
set_property PACKAGE_PIN AF30 [get_ports {ADC4_DB[8]}]
set_property PACKAGE_PIN AF28 [get_ports {ADC4_DB[9]}]
set_property PACKAGE_PIN AE30 [get_ports {ADC4_DB[10]}]
set_property PACKAGE_PIN AE29 [get_ports {ADC4_DB[11]}]
set_property PACKAGE_PIN AC29 [get_ports {ADC4_DB[12]}]
set_property PACKAGE_PIN AD29 [get_ports {ADC4_DB[13]}]
set_property PACKAGE_PIN AB29 [get_ports {ADC4_DB[14]}]
set_property PACKAGE_PIN AC30 [get_ports {ADC4_DB[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports ADC4_CS_FPGA]
set_property IOSTANDARD LVCMOS33 [get_ports ADC4_CONVST_FPGA]
set_property IOSTANDARD LVCMOS33 [get_ports ADC4_RESET_FPGA]
set_property IOSTANDARD LVCMOS33 [get_ports ADC4_RD_FPGA]
set_property IOSTANDARD LVCMOS33 [get_ports WR_4_FPGA]
set_property IOSTANDARD LVCMOS33 [get_ports ADC4_BUSY_FPGA]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC4_DB[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC4_DB[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC4_DB[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC4_DB[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC4_DB[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC4_DB[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC4_DB[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC4_DB[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC4_DB[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC4_DB[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC4_DB[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC4_DB[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC4_DB[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC4_DB[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC4_DB[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC4_DB[15]}]

##########ADC5
set_property PACKAGE_PIN D18 [get_ports ADC5_CS_FPGA]
set_property PACKAGE_PIN J18 [get_ports ADC5_CONVST_FPGA]
set_property PACKAGE_PIN D19 [get_ports ADC5_RESET_FPGA]
set_property PACKAGE_PIN E19 [get_ports ADC5_RD_FPGA]
set_property PACKAGE_PIN E20 [get_ports WR_5_FPGA]
set_property PACKAGE_PIN D21 [get_ports ADC5_BUSY_FPGA]
set_property PACKAGE_PIN G22 [get_ports {ADC5_DB[0]}]
set_property PACKAGE_PIN F22 [get_ports {ADC5_DB[1]}]
set_property PACKAGE_PIN H21 [get_ports {ADC5_DB[2]}]
set_property PACKAGE_PIN F21 [get_ports {ADC5_DB[3]}]
set_property PACKAGE_PIN H20 [get_ports {ADC5_DB[4]}]
set_property PACKAGE_PIN F20 [get_ports {ADC5_DB[5]}]
set_property PACKAGE_PIN G20 [get_ports {ADC5_DB[6]}]
set_property PACKAGE_PIN G19 [get_ports {ADC5_DB[7]}]
set_property PACKAGE_PIN H19 [get_ports {ADC5_DB[8]}]
set_property PACKAGE_PIN D17 [get_ports {ADC5_DB[9]}]
set_property PACKAGE_PIN H17 [get_ports {ADC5_DB[10]}]
set_property PACKAGE_PIN J19 [get_ports {ADC5_DB[11]}]
set_property PACKAGE_PIN J17 [get_ports {ADC5_DB[12]}]
set_property PACKAGE_PIN K18 [get_ports {ADC5_DB[13]}]
set_property PACKAGE_PIN L18 [get_ports {ADC5_DB[14]}]
set_property PACKAGE_PIN L17 [get_ports {ADC5_DB[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports ADC5_CS_FPGA]
set_property IOSTANDARD LVCMOS33 [get_ports ADC5_CONVST_FPGA]
set_property IOSTANDARD LVCMOS33 [get_ports ADC5_RESET_FPGA]
set_property IOSTANDARD LVCMOS33 [get_ports ADC5_RD_FPGA]
set_property IOSTANDARD LVCMOS33 [get_ports WR_5_FPGA]
set_property IOSTANDARD LVCMOS33 [get_ports ADC5_BUSY_FPGA]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC5_DB[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC5_DB[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC5_DB[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC5_DB[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC5_DB[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC5_DB[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC5_DB[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC5_DB[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC5_DB[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC5_DB[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC5_DB[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC5_DB[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC5_DB[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC5_DB[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC5_DB[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC5_DB[15]}]

###########################################################################
##  srio_txp_bp Interface
###########################################################################
create_clock -period 8.000 -name srio_refclk -waveform {0.000 4.000} [get_ports srio_refclkp_bp]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks srio_refclk]
set_property PACKAGE_PIN L8 [get_ports srio_refclkp_bp]
set_property PACKAGE_PIN T6 [get_ports {srio_rxp_bp[0]}]

###########################################################################
##  megnetic_out
###########################################################################
set_property PACKAGE_PIN H22 [get_ports {megnetic_out[0]}]
set_property PACKAGE_PIN D22 [get_ports {megnetic_out[1]}]
set_property PACKAGE_PIN C22 [get_ports {megnetic_out[2]}]
set_property PACKAGE_PIN E21 [get_ports {megnetic_out[3]}]
set_property PACKAGE_PIN C21 [get_ports {megnetic_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {megnetic_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {megnetic_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {megnetic_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {megnetic_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {megnetic_out[4]}]





set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property CONFIG_MODE SPIx4 [current_design]

set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_50m]
