###########################################################################
## GPIO 1V8
###########################################################################
set_property PACKAGE_PIN AN19 [get_ports {GPIO1V8[0]}]
set_property PACKAGE_PIN AM19 [get_ports {GPIO1V8[1]}]
set_property PACKAGE_PIN AT20 [get_ports {GPIO1V8[2]}]
set_property PACKAGE_PIN AR20 [get_ports {GPIO1V8[3]}]
set_property PACKAGE_PIN AU20 [get_ports {GPIO1V8[4]}]
set_property PACKAGE_PIN AW21 [get_ports {GPIO1V8[5]}]
set_property PACKAGE_PIN AT19 [get_ports {GPIO1V8[6]}]
set_property PACKAGE_PIN AP19 [get_ports {GPIO1V8[7]}]
set_property PACKAGE_PIN BC18 [get_ports {GPIO1V8[8]}]
set_property PACKAGE_PIN BC19 [get_ports {GPIO1V8[9]}]
set_property PACKAGE_PIN AW19 [get_ports {GPIO1V8[10]}]
set_property PACKAGE_PIN BB17 [get_ports {GPIO1V8[11]}]
set_property PACKAGE_PIN AV19 [get_ports {GPIO1V8[12]}]
set_property PACKAGE_PIN AY17 [get_ports {GPIO1V8[13]}]
set_property PACKAGE_PIN AU19 [get_ports {GPIO1V8[14]}]
set_property PACKAGE_PIN AV17 [get_ports {GPIO1V8[15]}]
set_property PACKAGE_PIN AR18 [get_ports {GPIO1V8[16]}]
set_property PACKAGE_PIN AT17 [get_ports {GPIO1V8[17]}]
set_property PACKAGE_PIN AN17 [get_ports {GPIO1V8[18]}]
set_property PACKAGE_PIN AP16 [get_ports {GPIO1V8[19]}]
set_property PACKAGE_PIN AM16 [get_ports {GPIO1V8[20]}]
set_property PACKAGE_PIN AM17 [get_ports {GPIO1V8[21]}]
set_property PACKAGE_PIN AL17 [get_ports {GPIO1V8[22]}]
set_property PACKAGE_PIN AL19 [get_ports {GPIO1V8[23]}]
set_property PACKAGE_PIN AM20 [get_ports {GPIO1V8[24]}]
set_property PACKAGE_PIN AL20 [get_ports {GPIO1V8[25]}]
set_property PACKAGE_PIN AP20 [get_ports {GPIO1V8[26]}]
set_property PACKAGE_PIN AN18 [get_ports {GPIO1V8[27]}]
set_property PACKAGE_PIN AV21 [get_ports {GPIO1V8[28]}]
set_property PACKAGE_PIN AU21 [get_ports {GPIO1V8[29]}]
set_property PACKAGE_PIN AY20 [get_ports {GPIO1V8[30]}]
set_property PACKAGE_PIN AW20 [get_ports {GPIO1V8[31]}]
set_property PACKAGE_PIN BD18 [get_ports {GPIO1V8[32]}]
set_property PACKAGE_PIN BD19 [get_ports {GPIO1V8[33]}]
set_property PACKAGE_PIN BB19 [get_ports {GPIO1V8[34]}]
set_property PACKAGE_PIN BC17 [get_ports {GPIO1V8[35]}]
set_property PACKAGE_PIN AY18 [get_ports {GPIO1V8[36]}]
set_property PACKAGE_PIN BA18 [get_ports {GPIO1V8[37]}]
set_property PACKAGE_PIN AV18 [get_ports {GPIO1V8[38]}]
set_property PACKAGE_PIN AW18 [get_ports {GPIO1V8[39]}]
set_property PACKAGE_PIN AT18 [get_ports {GPIO1V8[40]}]
set_property PACKAGE_PIN AU17 [get_ports {GPIO1V8[41]}]
set_property PACKAGE_PIN AP18 [get_ports {GPIO1V8[42]}]
set_property PACKAGE_PIN AR17 [get_ports {GPIO1V8[43]}]
set_property PACKAGE_PIN AN16 [get_ports {GPIO1V8[44]}]

set_property IOSTANDARD LVCMOS18 [get_ports {GPIO1V8[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO1V8[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO1V8[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO1V8[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO1V8[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO1V8[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO1V8[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO1V8[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO1V8[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO1V8[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO1V8[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO1V8[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO1V8[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO1V8[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO1V8[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO1V8[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO1V8[16]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO1V8[17]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO1V8[18]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO1V8[19]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO1V8[20]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO1V8[21]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO1V8[22]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO1V8[23]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO1V8[24]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO1V8[25]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO1V8[26]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO1V8[27]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO1V8[28]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO1V8[29]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO1V8[30]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO1V8[31]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO1V8[32]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO1V8[33]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO1V8[34]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO1V8[35]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO1V8[36]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO1V8[37]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO1V8[38]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO1V8[39]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO1V8[40]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO1V8[41]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO1V8[42]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO1V8[43]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO1V8[44]}]
###########################################################################
## I2C 0 and 1
###########################################################################
set_property PACKAGE_PIN AL21 [get_ports Z7_I2C0_SCL]
set_property PACKAGE_PIN AM21 [get_ports Z7_I2C0_SDA]
set_property PACKAGE_PIN AP21 [get_ports Z7_I2C1_SCL]
set_property PACKAGE_PIN AL22 [get_ports Z7_I2C1_SDA]
set_property IOSTANDARD LVCMOS33 [get_ports Z7_I2C0_SCL]
set_property IOSTANDARD LVCMOS33 [get_ports Z7_I2C0_SDA]
set_property IOSTANDARD LVCMOS33 [get_ports Z7_I2C1_SCL]
set_property IOSTANDARD LVCMOS33 [get_ports Z7_I2C1_SDA]
###########################################################################
## zynq gpio 3v3
###########################################################################
set_property PACKAGE_PIN AY23 [get_ports Z7_KU115_GPIO1]
set_property PACKAGE_PIN BA23 [get_ports Z7_KU115_GPIO2]
set_property PACKAGE_PIN BC23 [get_ports Z7_KU115_GPIO3]
set_property PACKAGE_PIN AY22 [get_ports Z7_KU115_GPIO4]
set_property PACKAGE_PIN BA22 [get_ports Z7_KU115_GPIO5]
set_property PACKAGE_PIN BA24 [get_ports Z7_KU115_GPIO6]
set_property IOSTANDARD LVCMOS33 [get_ports Z7_KU115_GPIO1]
set_property IOSTANDARD LVCMOS33 [get_ports Z7_KU115_GPIO2]
set_property IOSTANDARD LVCMOS33 [get_ports Z7_KU115_GPIO3]
set_property IOSTANDARD LVCMOS33 [get_ports Z7_KU115_GPIO4]
set_property IOSTANDARD LVCMOS33 [get_ports Z7_KU115_GPIO5]
set_property IOSTANDARD LVCMOS33 [get_ports Z7_KU115_GPIO6]
###########################################################################
## zynq ps gpio
###########################################################################
set_property PACKAGE_PIN AR28 [get_ports PS_GPIO0]
set_property PACKAGE_PIN AT28 [get_ports PS_GPIO1]
set_property PACKAGE_PIN AR27 [get_ports PS_GPIO2]
set_property IOSTANDARD LVCMOS18 [get_ports PS_GPIO0]
set_property IOSTANDARD LVCMOS18 [get_ports PS_GPIO1]
set_property IOSTANDARD LVCMOS18 [get_ports PS_GPIO2]




