###########################################################################
## SLR 0 clk
###########################################################################
set_property PACKAGE_PIN AV26 [get_ports SYSCLK1_SLR0_P]
set_property PACKAGE_PIN AW26 [get_ports SYSCLK1_SLR0_N]
set_property IOSTANDARD LVDS_25 [get_ports SYSCLK1_SLR0_P]
create_clock -period 10.000 -name SYSCLK1_SLR0_P -waveform {0.000 5.000} [get_ports SYSCLK1_SLR0_P]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks SYSCLK1_SLR0_P]

set_property PACKAGE_PIN AW28 [get_ports SYSCLK_SLR0]
set_property IOSTANDARD LVCMOS18 [get_ports SYSCLK_SLR0]
create_clock -period 10.000 -name SYSCLK_SLR0 -waveform {0.000 5.000} [get_ports SYSCLK_SLR0]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks SYSCLK_SLR0]
set_property LOC MMCME3_ADV_X2Y1 [get_cells clk_rst_wrapper_inst/clk_slr0_inst/inst/mmcme3_adv_inst]
###########################################################################
## SLR 1 clk
###########################################################################
set_property PACKAGE_PIN N32 [get_ports SYSCLK1_SLR1_P]
set_property PACKAGE_PIN N33 [get_ports SYSCLK1_SLR1_N]
set_property IOSTANDARD LVDS [get_ports SYSCLK1_SLR1_P]
create_clock -period 10.000 -name SYSCLK1_SLR1_P -waveform {0.000 5.000} [get_ports SYSCLK1_SLR1_P]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks SYSCLK1_SLR1_P]
set_property LOC MMCME3_ADV_X1Y7 [get_cells clk_rst_wrapper_inst/clk_diff_slr1_inst/inst/mmcme3_adv_inst]

set_property PACKAGE_PIN M31 [get_ports SYSCLK_SLR1]
set_property IOSTANDARD LVCMOS18 [get_ports SYSCLK_SLR1]
create_clock -period 10.000 -name SYSCLK_SLR1 -waveform {0.000 5.000} [get_ports SYSCLK_SLR1]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks SYSCLK_SLR1]

###########################################################################
##  srio_txp_4x Interface
###########################################################################
create_clock -period 8.000 -name srio_4x_refclk0 -waveform {0.000 4.000} [get_ports {srio_refclkp_4x[0]}]
create_clock -period 8.000 -name srio_4x_refclk1 -waveform {0.000 4.000} [get_ports {srio_refclkp_4x[1]}]
create_clock -period 8.000 -name srio_4x_refclk2 -waveform {0.000 4.000} [get_ports {srio_refclkp_4x[2]}]
create_clock -period 8.000 -name srio_4x_refclk3 -waveform {0.000 4.000} [get_ports {srio_refclkp_4x[3]}]
create_clock -period 8.000 -name srio_4x_refclk4 -waveform {0.000 4.000} [get_ports {srio_refclkp_4x[4]}]
create_clock -period 8.000 -name srio_4x_refclk5 -waveform {0.000 4.000} [get_ports {srio_refclkp_4x[5]}]
create_clock -period 8.000 -name srio_4x_refclk6 -waveform {0.000 4.000} [get_ports {srio_refclkp_4x[6]}]
create_clock -period 8.000 -name srio_4x_refclk7 -waveform {0.000 4.000} [get_ports {srio_refclkp_4x[7]}]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks srio_4x_refclk0]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks srio_4x_refclk1]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks srio_4x_refclk2]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks srio_4x_refclk3]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks srio_4x_refclk4]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks srio_4x_refclk5]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks srio_4x_refclk6]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks srio_4x_refclk7]
set_property PACKAGE_PIN AW9 [get_ports {srio_refclkp_4x[0]}]
set_property PACKAGE_PIN AT11 [get_ports {srio_refclkp_4x[1]}]
set_property PACKAGE_PIN AM11 [get_ports {srio_refclkp_4x[2]}]
set_property PACKAGE_PIN AH11 [get_ports {srio_refclkp_4x[3]}]
set_property PACKAGE_PIN AD11 [get_ports {srio_refclkp_4x[4]}]
set_property PACKAGE_PIN Y11 [get_ports {srio_refclkp_4x[5]}]
set_property PACKAGE_PIN T11 [get_ports {srio_refclkp_4x[6]}]
set_property PACKAGE_PIN BA40 [get_ports {srio_refclkp_4x[7]}]

set_property PACKAGE_PIN BC2 [get_ports {srio_rxp_4x[0]}]
set_property PACKAGE_PIN BA2 [get_ports {srio_rxp_4x[1]}]
set_property PACKAGE_PIN AW4 [get_ports {srio_rxp_4x[2]}]
set_property PACKAGE_PIN AV2 [get_ports {srio_rxp_4x[3]}]
set_property PACKAGE_PIN AU4 [get_ports {srio_rxp_4x[4]}]
set_property PACKAGE_PIN AT2 [get_ports {srio_rxp_4x[5]}]
set_property PACKAGE_PIN AR4 [get_ports {srio_rxp_4x[6]}]
set_property PACKAGE_PIN AP2 [get_ports {srio_rxp_4x[7]}]
set_property PACKAGE_PIN AN4 [get_ports {srio_rxp_4x[8]}]
set_property PACKAGE_PIN AM2 [get_ports {srio_rxp_4x[9]}]
set_property PACKAGE_PIN AL4 [get_ports {srio_rxp_4x[10]}]
set_property PACKAGE_PIN AK2 [get_ports {srio_rxp_4x[11]}]
set_property PACKAGE_PIN AJ4 [get_ports {srio_rxp_4x[12]}]
set_property PACKAGE_PIN AH2 [get_ports {srio_rxp_4x[13]}]
set_property PACKAGE_PIN AG4 [get_ports {srio_rxp_4x[14]}]
set_property PACKAGE_PIN AF2 [get_ports {srio_rxp_4x[15]}]
set_property PACKAGE_PIN AE4 [get_ports {srio_rxp_4x[16]}]
set_property PACKAGE_PIN AD2 [get_ports {srio_rxp_4x[17]}]
set_property PACKAGE_PIN AC4 [get_ports {srio_rxp_4x[18]}]
set_property PACKAGE_PIN AB2 [get_ports {srio_rxp_4x[19]}]
set_property PACKAGE_PIN AA4 [get_ports {srio_rxp_4x[20]}]
set_property PACKAGE_PIN Y2 [get_ports {srio_rxp_4x[21]}]
set_property PACKAGE_PIN W4 [get_ports {srio_rxp_4x[22]}]
set_property PACKAGE_PIN V2 [get_ports {srio_rxp_4x[23]}]
set_property PACKAGE_PIN U4 [get_ports {srio_rxp_4x[24]}]
set_property PACKAGE_PIN T2 [get_ports {srio_rxp_4x[25]}]
set_property PACKAGE_PIN R4 [get_ports {srio_rxp_4x[26]}]
set_property PACKAGE_PIN P2 [get_ports {srio_rxp_4x[27]}]
set_property PACKAGE_PIN BC45 [get_ports {srio_rxp_4x[28]}]
set_property PACKAGE_PIN BA45 [get_ports {srio_rxp_4x[29]}]
set_property PACKAGE_PIN AW45 [get_ports {srio_rxp_4x[30]}]
set_property PACKAGE_PIN AV43 [get_ports {srio_rxp_4x[31]}]

###########################################################################
##  srio_txp_1x Interface
###########################################################################
create_clock -period 8.000 -name srio_1x_refclk0 -waveform {0.000 4.000} [get_ports {srio_refclkp_1x[0]}]
create_clock -period 8.000 -name srio_1x_refclk1 -waveform {0.000 4.000} [get_ports {srio_refclkp_1x[1]}]
create_clock -period 8.000 -name srio_1x_refclk2 -waveform {0.000 4.000} [get_ports {srio_refclkp_1x[2]}]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks srio_1x_refclk0]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks srio_1x_refclk1]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks srio_1x_refclk2]
set_property PACKAGE_PIN M11 [get_ports {srio_refclkp_1x[0]}]
set_property PACKAGE_PIN H11 [get_ports {srio_refclkp_1x[1]}]
set_property PACKAGE_PIN D11 [get_ports {srio_refclkp_1x[2]}]

set_property PACKAGE_PIN N4 [get_ports {srio_rxp_1x[0]}]
set_property PACKAGE_PIN M2 [get_ports {srio_rxp_1x[1]}]
set_property PACKAGE_PIN L4 [get_ports {srio_rxp_1x[2]}]
set_property PACKAGE_PIN K2 [get_ports {srio_rxp_1x[3]}]
set_property PACKAGE_PIN J4 [get_ports {srio_rxp_1x[4]}]
set_property PACKAGE_PIN H2 [get_ports {srio_rxp_1x[5]}]
set_property PACKAGE_PIN G4 [get_ports {srio_rxp_1x[6]}]
set_property PACKAGE_PIN F2 [get_ports {srio_rxp_1x[7]}]
set_property PACKAGE_PIN E4 [get_ports {srio_rxp_1x[8]}]
set_property PACKAGE_PIN D2 [get_ports {srio_rxp_1x[9]}]
set_property PACKAGE_PIN C4 [get_ports {srio_rxp_1x[10]}]
set_property PACKAGE_PIN A5 [get_ports {srio_rxp_1x[11]}]

